---
trigger:
  - main
stages:
  - stage: build
    displayName: Build Stage
    pool: 
      name: default
    jobs:
      -  job: maven
         displayName: Build using maven
         steps:
           - task: Maven@4
             inputs:
               mavenPomFile: 'pom.xml' 
               goals: package
