---
trigger:
  - main
stages:
  - stage: build
    displayName: Build Stage
    pool: 
      name: Default
      demands:
        - Agent.Version -gtVersion 2.163.1


    jobs:
      -  job: maven
         displayName: Build using maven
         steps:
           - task: Maven@4
             inputs:
               mavenPomFile: 'pom.xml' 
               goals: package
